{% set name = "great-expectations" %}
{% set version = "0.4.2" %}
{% set sha256 = "41fe76f96d82ad27587dad13b9064ac73c942e8f7355912d36d8167f3a2f039b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-","_") }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  #noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.9.2
    - scipy >=0.19.0
    - pandas >=0.20.3
    - python-dateutil >=2.4.2
    - pytz >=2015.6
    - argh >=0.26.2
    - jsonschema >=2.5.1
    - six >=1.9.0
    - sqlalchemy >=1.2

test:
  imports:
    - great_expectations

about:
  home: https://github.com/great-expectations/great_expectations
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Always know what to expect from your data.'

  description: |
    Great Expectations is a framework that helps teams save time and
    promote analytic integrity with a new twist on automated "testing:"
    pipeline tests. Pipeline tests are applied to data (instead of code)
    and at batch time (instead of compile or deploy time).

    Software developers have long known that automated testing is
    essential for managing complex codebases. Great Expectations brings
    the same discipline, confidence, and acceleration to data science
    and engineering teams.
  doc_url: http://readthedocs.org/projects/great-expectations/
  dev_url: https://github.com/great-expectations/great_expectations

extra:
  recipe-maintainers:
    - sodre
    - jpcampb2
