{% set name = "great-expectations" %}
{% set version = "1.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 8f24975673b2795bd18c25b587e4c674609347184a1a638fa7eaf209c6c3dabb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - versioneer ==0.29
    - typing_extensions >=4.1.0
  run:
    - python
    - altair >=4.2.1,<5.0.0
    - cryptography >=3.2
    - jinja2 >=3
    - jsonschema >=2.5.1
    - marshmallow >=3.7.1,<4.0.0
    - mistune >=0.8.4
    - numpy >=1.21.6  # [py==39]
    - numpy >=1.22.4  # [py>=310 and py<312]
    - numpy >=1.26.0  # [py==312]
    - numpy >=2.1.0  # [py>=313]
    - packaging
    - pandas >=1.1.3  # [py==39]
    - pandas >=1.3.0  # [py>=310 and py<313]
    - pandas >=2.2.3  # [py>=313]
    - pydantic >=1.10.7
    - pyparsing >=2.4,!=3.2.4
    - python-dateutil >=2.8.1
    - requests >=2.20
    - ruamel.yaml >=0.16
    - scipy >=1.6.0
    - tqdm >=4.59.0
    - typing-extensions >=4.1.0
    - tzlocal >=1.2

# No need to test doc generation.
{% set ignore_tests = " --ignore=tests/core/test__docs_decorators.py" %}
# Need to set up a localhost server, can`t find in the upstream repo for an example.
{% set deselect_tests = " --deselect=tests/core/test_validation_definition.py::TestValidationRun::test_adds_correct_batch_parameter_fields_for_postgres" %}
# PySpark cannot locate the Python interpreter on win
{% set deselect_tests = deselect_tests + " --deselect=tests/core/test_serialization.py::test_serialization_of_spark_df" %}  # [win]
test:
  source_files:
    - tests
  imports:
    - great_expectations
    - great_expectations.alias_types
    - great_expectations.checkpoint
    - great_expectations.compatibility
    - great_expectations.constants
    - great_expectations.core
    - great_expectations.data_context
    - great_expectations.datasource
    - great_expectations.exceptions
    - great_expectations.execution_engine
    - great_expectations.expectations
    - great_expectations.experimental
    - great_expectations.metrics
    - great_expectations.render
    - great_expectations.self_check
    - great_expectations.types
    - great_expectations.types.base
    - great_expectations.util
    - great_expectations.validator
    - great_expectations.warnings
  requires:
    - pip
    - pytest
    - responses
    - freezegun >=0.3.15
    - pytest-mock >=3.14.0
    - sqlalchemy
    - psycopg2 >=2.7.6
    - pyspark >=2.3.2
    - boto3 >=1.17.106
    - postgresql
    - openjdk 17.*
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest tests/core {{ deselect_tests }} {{ ignore_tests }}

about:
  home: https://github.com/great-expectations/great_expectations
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Always know what to expect from your data.

  description: |
    Great Expectations helps teams save time and promote analytic integrity
    by offering a unique approach to automated testing: pipeline tests.
    Pipeline tests are applied to data (instead of code) and at batch time
    (instead of compile or deploy time). Pipeline tests are like unit tests
    for datasets: they help you guard against upstream data changes and monitor
    data quality.

    Software developers have long known that automated testing is
    essential for managing complex codebases. Great Expectations brings
    the same discipline, confidence, and acceleration to data science
    and engineering teams.
  doc_url: https://docs.greatexpectations.io
  dev_url: https://github.com/great-expectations/great_expectations

extra:
  recipe-maintainers:
    - sodre
    - jcampbell
    - xhochy
    - alexsherstinsky
    - anthonyburdi
    - talagluck
    - Shinnnyshinshin
    - janjagusch
    - cdkini
  skip-lints:
    - host_section_needs_exact_pinnings
