{% set version = "1.3.8" %}

package:
  name: great-expectations
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/great-expectations/great_expectations-{{ version }}.tar.gz
  sha256: 60da354d5cb0be07291f985966ff66800af9dee0d2c16e8af6efb9d1a9b39adf

build:
  skip: True  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - altair >=4.2.1,<5.0.0
    - cryptography >=3.2
    - jinja2 >=3
    - jsonschema >=2.5.1
    - marshmallow >=3.7.1,<4.0.0
    - mistune >=0.8.4
    - numpy >=1.21.6  # [py==39]
    - numpy >=1.22.4  # [py>=310 and py<312]
    - numpy >=1.26.0  # [py>=312]
    - packaging
    - pandas >=1.1.3,<2.2  # [py==39]
    - pandas >=1.3.0,<2.2  # [py>=310 and py<312]
    - pandas <2.2  # [py>=312]
    - posthog >3,<4
    - pydantic >=1.10.7
    - pyparsing >=2.4
    - python-dateutil >=2.8.1
    - requests >=2.20
    - ruamel.yaml >=0.16
    - scipy >=1.6.0
    - tqdm >=4.59.0
    - typing-extensions >=4.1.0
    - tzlocal >=1.2
    - python
  run_constrained:
    - sqlalchemy >=1.3.16
    - pyspark >=2.3.2
    # Extra: arrow
    - feather-format >=0.4.1
    # Extra: athena
    - pyathena <3,>=2.0.0
    - sqlalchemy >=1.4.0,<2.0.0
    # Extra: s3
    - boto3 >=1.17.106
    # Extra: azure_secrets
    - azure-identity >=1.10.0
    - azure-keyvault-secrets >=4.0.0
    - azure-storage-blob >=12.5.0
    # Extra: gcp
    - gcsfs >=0.5.1
    - google-cloud-bigquery-core >=3.3.6
    - google-cloud-bigquery-storage >=2.20.0
    - google-cloud-secret-manager >=1.0.0
    - google-cloud-storage >=2.10.0  # [py>=311]
    - google-cloud-storage >=1.28.0  # [py<311]
    - sqlalchemy-bigquery >=1.3.0
    # Extra: clickhouse
    - clickhouse-sqlalchemy >=0.2.2  # [py<312]
    - clickhouse-sqlalchemy >=0.3.0  # [py>=312]
    # Extra: cloud
    - orjson >=3.9.7
    # Extra: databricks
    - databricks-sqlalchemy >=1.0.0
    # Extra: mssql
    - pyodbc >=4.0.30
    # Extra: dremio
    - sqlalchemy-dremio ==1.2.1
    # Extra: excel
    - openpyxl >=3.0.7
    - xlrd >=1.1.0,<2.0.0
    # Extra: hive
    - PyHive >=0.6.5
    - thrift >=0.16.0
    - thrift-sasl >=0.4.3
    # Extra: mysql
    - PyMySQL >=1.1.1
    # Extra: pagerduty
    - pypd ==1.1.0
    # Extra: postgresql
    - psycopg2-binary >=2.7.6
    # Extra: redshift
    - sqlalchemy-redshift >=0.8.8
    # Extra: snowflake
    - snowflake-connector-python >=2.5.0 # [py<311]
    - snowflake-connector-python >2.9.0  # [py>=311]
    - snowflake-sqlalchemy >=1.2.3,!=1.7.0

test:
  imports:
    - great_expectations
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/great-expectations/great_expectations
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Always know what to expect from your data.

  description: |
    Great Expectations helps teams save time and promote analytic integrity
    by offering a unique approach to automated testing: pipeline tests.
    Pipeline tests are applied to data (instead of code) and at batch time
    (instead of compile or deploy time). Pipeline tests are like unit tests
    for datasets: they help you guard against upstream data changes and monitor
    data quality.

    Software developers have long known that automated testing is
    essential for managing complex codebases. Great Expectations brings
    the same discipline, confidence, and acceleration to data science
    and engineering teams.
  doc_url: https://docs.greatexpectations.io
  dev_url: https://github.com/great-expectations/great_expectations

extra:
  recipe-maintainers:
    - sodre
    - jcampbell
    - xhochy
    - alexsherstinsky
    - anthonyburdi
    - talagluck
    - Shinnnyshinshin
    - janjagusch
    - cdkini
