travis:
  secure:
    BINSTAR_TOKEN: WUIBN9iWhpVbNU5MEHGW62hj6j7k8tPdzbitEGvu0Pu1o0PTjJOino3Lw19ms2cZTbRfendff+IkFmax/Q8vmRd5+8yIQZwFXZnHH5Sm7GLKhygdq0zhb0Vrn6QUQSZ6HqEV58o6brLLgLMjqM5Bgc48Pmm/l/ljS6IJtkkY5L2Akw9jn4QFGaxFGkRoyhF2Fa1Kjq4uafHKHSVrzH4YN93Xx1Z65jKLCTewGFcmCkckbm3vVPqhmxzghBYdeteOWItSUn97QvclbbMyoc2uguWt9ZqV4p6yAGrAtz4/9Bpa9DV7ighgmNsMzd/jkhxulpY0njKzRH3ksQyMW4ebrWmrPyoSNHKruCpezaM1pNNwSArS3ISJgEEHFdKXvY8E6Psixz98xkpgiFBcTq2IlaTQ/3beHJgzDIOinDIHLZoRzfXON3BbVtlVTaQyAxXPbHkWPtQ6YRnD6WbL1D1WmB6PiliikgXsdbH7Ee4JRxZ9jtcIy4fkUr9BNDfjkkksS13NsZfy/m5gzCP68acFrFeofE4Em/5bDwljxiOS2QIqDzEGW82QQuzS41g6aK74AxB2vMxWM/zR4krCmvWRRNHH1DAa8nQHw9qxv2M/gmaCQIBazfgs5ubZl6kLPIzem/+8lCvfLUHMvoqplCeamKDKT7MNICGzP7gd8Xp0AwY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
